## advanced array creation 

In [1]:
#meshgrid (for plotting , calculation)
import numpy as np 
x = np.array([1,2,3])
y = np.array([4,5])
x , y = np.meshgrid(x,y)
print(x,y)

[[1 2 3]
 [1 2 3]] [[4 4 4]
 [5 5 5]]


In [7]:
# random sampling 
np.random.seed(42) #for reproducibility

#random choice from array
arr = np.array([1,2,3,4,5,6])
sample = np.random.choice(arr,size = 3,replace = False) #replace = false means it will never choose the same digit
print(sample)

#Random shuffle
print(np.random.shuffle(arr))
print(arr)

#random with specefic distribution 
normal = np.random.normal(loc = 0, scale = 1, size = 1000)
print(normal)

uniform = np.random.uniform(low = 0, high = 10,size = 1000)
print(uniform)


[1 2 6]
None
[4 1 2 3 6 5]
[-9.46210019e-02 -9.28828100e-01 -8.85230346e-01 -4.12188480e-01
 -4.82618796e-01  1.64164820e-01  2.33095239e-01  1.17994612e-01
  1.46237812e+00  1.53871497e+00 -2.43910582e+00  6.03441225e-01
 -2.51043968e-01 -1.63867116e-01 -1.47632969e+00  1.48698096e+00
 -2.44551775e-02  3.55551317e-01  4.17011110e-01  8.32461857e-01
 -2.93399146e-01 -2.98385694e-02  9.51257843e-02  6.64654343e-01
 -1.40218497e-01 -3.31934001e-02 -7.49076523e-01 -7.78382007e-01
  9.48842858e-01  1.58085059e+00 -3.68170941e-01  3.75564634e-01
 -1.19315823e+00 -4.09051902e-01 -4.46741471e-01  1.52424163e+00
  3.22999797e-01 -1.39341694e+00 -2.17833425e+00 -1.04389641e+00
  1.72693707e-01  3.24198768e-01  7.45859542e-01 -1.83658324e+00
  5.64464239e-01  2.55006681e-02  4.73193249e-01  6.59190598e-01
  2.34074633e+00  1.07098519e+00  9.64164790e-02  4.19102106e-01
 -9.53027789e-01 -1.04787060e+00 -1.87567677e+00 -1.36678214e+00
  6.36305108e-01 -9.06720669e-01  4.76042587e-01  1.30366127e+0

In [10]:
arr = np.array([1,2,3,4,5])

#view (shares memory)
view = arr[:]
view[0] = 999
print(arr) # - original changed 

#copy(independent)
copy = arr.copy()
copy[0] = 111


#check if view or copy
print(view.base is arr)
print(copy.base is None)


[999   2   3   4   5]
True
True


In [ ]:
#medical image processing 
np.random.seed(42) 
image = np.random.randint(0,256,(100,100)) # 100x100 pixels

print("\n" + "="*60)
print(f"{'Medical image processing' :^60}")
print("="*60)

# image statistics
print(f"\nImage shape: {image.shape}")
print(f"Image size : {image.size} pixels")
print(f"Min Intensity: {np.min(image)}")
print(f"Max intensity: {np.max(image)}")
print(f"Mean intensity: {np.mean(image): .2f}")


#appply threshold(segment image)
threshold = 128
binary_image = image > threshold
print(f"\nPixels above thresold: {np.sum(binary_image)}")
print(f"Percentage : {np.mean(binary_image)* 100:.1f}%")

#histogram(intensity distribution)
hist, bins = np.histogram(image, bins = 10) # it means it will divide all values into 10 groups
print(f"\nIntensity distribution(10bins):")
for i in range(len(hist)):
    print(f"{bins[i]:.0f}-{bins[i+1]:.0f}:{hist[i]} pixels")

#apply smoothing
kernel_size = 3

smoothed = np.zeros_like(image,dtype = float)



                  Medical image processing                  

Image shape: (100, 100)
Image size : 10000 pixels
Min Intensity: 0
Max intensity: 255
Mean intensity:  127.68

Pixels above thresold: 4988
Percentage : 49.9%

Intensity distribution(10bins):
0-26:1010 pixels
26-51:941 pixels
51-76:995 pixels
76-102:970 pixels
102-128:1053 pixels
128-153:1018 pixels
153-178:1055 pixels
178-204:973 pixels
204-230:1008 pixels
230-255:977 pixels


Histogram Returns TWO Things

Actually:

counts, bin_edges = np.histogram(image, bins=10)


counts → number of pixels in each bin

bin_edges → the boundaries of the bins

Example:

counts = [200, 350, 900, 600, ...]
bin_edges = [0, 25, 50, 75, 100]


Meaning:

Between 0–25, you have 200 pixels