## universal mathematics functioons 


In [2]:
import numpy as np
arr = np.array([0,30,45,50,60,90])
print(np.sin(np.radians(arr)))
print(np.cos(np.radians(arr)))
print(np.tan(np.radians(arr)))




[0.         0.5        0.70710678 0.76604444 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 6.42787610e-01
 5.00000000e-01 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.19175359e+00
 1.73205081e+00 1.63312394e+16]


# # exponential and logarithm

In [6]:
arr = np.array([1,2,3,4,5,6,10])
print(np.exp(arr)) ## e = 2.71828 it will provide outcome of e to the power x = 1, 2. 3,4,5
print(np.log(arr)) # Natural log
print(np.log10(arr))
print(np.sqrt(arr))



[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 2.30258509]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 1.        ]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 3.16227766]


### rounding 

In [7]:
arr = np.array([1.234, 2.567, 3.879])
print(np.round(arr,2)) # it will find 2 didgits from point 
print(np.floor(arr))
print(np.ceil(arr))


[1.23 2.57 3.88]
[1. 2. 3.]
[2. 3. 4.]


## absolute value 


In [ ]:
arr = np.array([-1,-2,3,-4])
print(np.abs(arr)) # it will find mode value of every number or absolute value 



[1 2 3 4]


### lets do advanced math 

In [14]:
#broadcasting 
arr = np.array([[2,3,4,],
                [11,12,13]])
print(arr + 10)

## lets add 2d array with 2d array 
row = np.array([2,4,5])
print(arr +row )

## column broadcastes 
col = np.array([[11],[12]])
print(row + col)

arr1 = np.array([1,2,3]).reshape(3,1)
print(arr1)
arr2 = np.array([2,4,5,8,9])
results = arr1 + arr2
print(results)

print()

[[12 13 14]
 [21 22 23]]
[[ 4  7  9]
 [13 16 18]]
[[13 15 16]
 [14 16 17]]
[[1]
 [2]
 [3]]
[[ 3  5  6  9 10]
 [ 4  6  7 10 11]
 [ 5  7  8 11 12]]



## linear algebra 

In [3]:
## matrix multiplication 
A = np.array([[1,4],[6,7]])
B = np.array([[1,18],[23,9]])
c = np.dot(A,B)
C = A @ B
print(c)
print(C)

[[ 93  54]
 [167 171]]
[[ 93  54]
 [167 171]]


In [4]:
## matrix operationns 
import numpy as np
print(np.linalg.det(A))


-17.0
