numpy install
pip install numpy

## Basics 

In [1]:
import numpy as np

print(np.__version__)

2.1.2


In [ ]:
arr1d = np.array([1,2,3,4,5])
print(arr1d)

##2d array
arr2d = np.array([[1,2,3,4],
                  [1,2,3,4]])
print(f"this is 2d array\n{arr2d}")
## 3d arry
arr3d = np.array([[[1,2],[2,3]],
                  [[4,5],[7,8]]])
print(arr3d)
print(arr3d.shape)


[1 2 3 4 5]
this is 2d array
[[1 2 3 4]
 [1 2 3 4]]
[[[1 2]
  [2 3]]

 [[4 5]
  [7 8]]]
(2, 2, 2)


### using bultin  functions 

In [24]:
zeros = np.zeros(5)
zeros2d = np.zeros((3,4))
print(f" 1d {zeros} and 2d \n{zeros2d}")

# empty  array 
empty = np.empty(5)
print(f" this is empty :{empty}")
# array with specific value
full = np.full(5,7)
full2d = np.full((5,7),10) 
print(f" this is full with same  numeber : {full} and {full2d}")

# range of values 
range_arr = np.arange(0,10)
range_step = np.arange(0,10,3)
print(f" it will find range of array {range_arr} and  if it will steps at 3 {range_step}")
# evenly spaced value 
linespace = np.linspace(0,1,5)
print(f" it eill fine linespace of float value {linespace}")

 1d [0. 0. 0. 0. 0.] and 2d 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 this is empty :[0. 0. 0. 0. 0.]
 this is full with same  numeber : [7 7 7 7 7] and [[10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]]
 it will find range of array [0 1 2 3 4 5 6 7 8 9] and  if it will steps at 3 [0 3 6 9]
 it eill fine linespace of float value [0.   0.25 0.5  0.75 1.  ]


## welcome to matrix 


In [25]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:

random = np.random.rand(5)  ##(5)refers how ma #random values within 0 to 1
print(random)
random_int = np.random.randint(0,100,3)
print(random_int)
# normal distribution
random_normal = np.random.randn(5)
print(random_normal)

[0.82053481 0.37735314 0.12252774 0.5644738  0.01933247]
[32  6 80]
[ 0.23649099 -0.92456965  0.50754151  0.00449461 -0.61134962]


## array properties



In [34]:
arr =np.array([[2,3,4,5,6],
               [5,6,7,8,9]])
print(f" it will provide dimension of {arr.ndim}")
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

 it will provide dimension of 2
(2, 5)
10
int64
8
80


## data types

In [41]:
# specify data typee
arr_int = np.array([1,2,3],dtype = np.int32)
print(arr_int)
arr_float = np.array([1,2,3],dtype = np.float64)
print(arr_float)
arr_bool= np.array([1,2,3],dtype = bool)
print(arr_bool)


[1 2 3]
[1. 2. 3.]
[ True  True  True]


### basics indexing 
arr = np.array([2,3,4,5,6,7,8])

In [45]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[0])
print(arr[-1])
print(arr[1:4]) # it will slice from  1 index to 4 index before 
print(arr[:4]) # it will return till index 2 
print(arr[2:]) # it will rturn from index 2 to end 
print(arr[::2])


1
7
[2 3 4]
[1 2 3 4]
[3 4 5 6 7]
[1 3 5 7]


In [ ]:
## lets go for 2d 
arr =np.array([[1,2,3,4,5],
               [1,2,3,4,5]])

print(arr[0,0])
print(arr[1,2])
print(arr[0])
print(arr[:,0])
print(arr[0:2,1:3]) # 0:2 mention rows where starting from 0 to 1 excluded and from 1 to 2 columns, 3 excluded

1
3
[1 2 3 4 5]
[1 1]
[[2 3]
 [2 3]]


In [5]:
## basics operations 
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr + 10)
print(arr * 2)
print(arr**2)
print(arr /2)

#operation between arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6]) 
print(arr1 + arr2)
print(arr1 *arr2)

# comparison operations
arr = np.array ([1,2,3,4,5])
print(arr > 3)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]
[5 7 9]
[ 4 10 18]
[False False False  True  True]


## intermediate 
boolean and fancy indexing 



In [ ]:
arr = np.array([10,202,30,40,50])

# boolean  indexing 
mask = arr > 25 
print(mask)
print(arr[mask])
#indexing directly 
print(arr[arr>10])
print(arr[(arr > 15) &(arr < 100)])

#fancy indexing 
indices = np.array([0,2,4])
arr2d = np.array([[1,3,4],
                  [9,7,9],
                  [3,5,7]])
print(arr2d[arr2d > 2])



[False  True  True  True  True]
[202  30  40  50]
[202  30  40  50]
[30 40 50]
[3 4 9 7 9 3 5 7]


### array manipulation 


In [18]:
arr = np.array([[1,2,3],
                [4,5,6],
                [8,9,10]])
#reshaped = arr.reshape(5,2) ## make sure when youre reshaping matrix should match with total number ar asset



In [ ]:
flat = arr.flatten() # flatten the array provided
print(flat)
flat = arr.ravel()# need to check 
print(flat)

#transpose

transposed = arr.T #it will transpose into t shape  means rows reshaped to column 
print(transposed)

## add dimensions
expanded = np.expand_dims(arr, axis = 0) #it willl reshape from transposed expanded  
print(expanded)

#remove dimension
squeezed = np.squeeze(expanded)
print(squeezed) #it can reshaped or squezzed to remove one dimension


[ 1  2  3  4  5  6  8  9 10]
[ 1  2  3  4  5  6  8  9 10]
[[ 1  4  8]
 [ 2  5  9]
 [ 3  6 10]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


## concatenation and splitting 


In [27]:
arr1 = np.array([[1,3],[3,4]])
arr2 = np.array([[4,5],[2,4]])

#concatanet vertically
verticle = np.vstack([arr1,arr2])
print(verticle)
horizontal = np.concatenate([arr1,arr2])
print(horizontal)

## split
arr = np.arange(12).reshape(3,4)
split =np.split(arr,3,axis = 0)
print(split)

[[1 3]
 [3 4]
 [4 5]
 [2 4]]
[[1 3]
 [3 4]
 [4 5]
 [2 4]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


### statstical operations 


In [33]:
arr = np.array([2,3,5,6,7,8,9,10,20,40])
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.sum(arr))
print(np.prod(arr))

# 2d arra 
arr = np.array([[1,3,4],
                [4,5,6]])
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.sum(arr))
print(np.prod(arr))


7.5
11.0
10.761040841851685
115.8
110
725760000
4.0
3.8333333333333335
1.5723301886761007
2.4722222222222228
23
1440
